# ==============================================
# THREAD SPECIFICATIONS (ISO Metric Coarse)
# ==============================================
# D: Nominal diameter [mm] (呼び径)
# d: Screw Minor diameter [mm] (谷径)
# P: Pitch [mm]
#
# Stress area As is calculated as:
# As = 0.7854 × (d - 0.9382 × P)² [mm²]
# ==============================================

# based on ISO 261
threads:
  M2:   { D: 2,  d: 1.51,  P: 0.4 }
  M2.5: { D: 2.5, d: 1.95,  P: 0.45 }
  M3:   { D: 3,  d: 2.39,  P: 0.5 }
  M4:   { D: 4,  d: 3.14,  P: 0.7 }
  M5:   { D: 5,  d: 4.02,  P: 0.8 }
  M6:   { D: 6,  d: 4.77,  P: 1.0 }
  M8:   { D: 8,  d: 6.47,  P: 1.25 }
  M10:  { D: 10, d: 8.16,  P: 1.5 }
  M12:  { D: 12, d: 9.86,  P: 1.75 }
  M14:  { D: 14, d: 11.55, P: 2.0 }
  M16:  { D: 16, d: 13.55, P: 2.0 }
  M18:  { D: 18, d: 15.93, P: 2.5 }
  M20:  { D: 20, d: 17.93, P: 2.5 }
  M22:  { D: 22, d: 19.93, P: 2.5 }
  M24:  { D: 24, d: 21.82, P: 3.0 }
  M27:  { D: 27, d: 24.82, P: 3.0 }
  M30:  { D: 30, d: 27.71, P: 3.5 }
