# ==============================================
# THREAD SPECIFICATIONS (ISO Metric Coarse)
# ==============================================
# d: Screw Minor diameter [mm]
# P: Pitch [mm]
#
# Stress area As is calculated as:
# As = 0.7854 × (d - 0.9382 × P)² [mm²]
# ==============================================

# based on ISO 261
threads:
  M2:   { d: 1.51,  P: 0.4 }
  M2.5: { d: 1.95,  P: 0.45 }
  M3:  { d: 2.39,  P: 0.5 }
  M4:  { d: 3.14,  P: 0.7 }
  M5:  { d: 4.02,  P: 0.8 }
  M6:  { d: 4.77,  P: 1.0 }
  M8:  { d: 6.47,  P: 1.25 }
  M10: { d: 8.16,  P: 1.5 }
  M12: { d: 9.86,  P: 1.75 }
  M14: { d: 11.55, P: 2.0 }
  M16: { d: 13.55, P: 2.0 }
  M18: { d: 15.93, P: 2.5 }
  M20: { d: 17.93, P: 2.5 }
  M22: { d: 19.93, P: 2.5 }
  M24: { d: 21.82, P: 3.0 }
  M27: { d: 24.82, P: 3.0 }
  M30: { d: 27.71, P: 3.5 }
